package tech.wenisch.smtp2x.config;

import jakarta.servlet.*; import jakarta.servlet.http.*; import java.io.IOException; import org.springframework.beans.factory.ObjectProvider; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.core.*; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.core.userdetails.*; import org.springframework.security.crypto.factory.PasswordEncoderFactories; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.oauth2.client.registration.ClientRegistrationRepository; import org.springframework.security.web.*; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.web.filter.OncePerRequestFilter; import org.springframework.stereotype.Component; import tech.wenisch.smtp2x.domain.*; import tech.wenisch.smtp2x.repository.AppUserRepository; import tech.wenisch.smtp2x.service.AuditService;

@Configuration @EnableMethodSecurity public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return PasswordEncoderFactories.createDelegatingPasswordEncoder();}
 @Bean UserDetailsService userDetailsService(AppUserRepository users){return email->{AppUser u=users.findByEmailIgnoreCase(email).orElseThrow(()->new UsernameNotFoundException(email));if(u.isOidcOnly())throw new UsernameNotFoundException(email);return User.withUsername(u.getEmail()).password(u.getPasswordHash()).authorities(new SimpleGrantedAuthority("ROLE_"+u.getRole())).disabled(!u.isEnabled()).build();};}
 @Bean SecurityFilterChain security(HttpSecurity http,PendingUserFilter pending,OidcUserService oidc,Smtp2xProperties properties,ObjectProvider<ClientRegistrationRepository> clients)throws Exception{http.authorizeHttpRequests(a->a.requestMatchers("/login","/css/**","/js/**","/actuator/health/**").permitAll().anyRequest().authenticated()).formLogin(f->f.loginPage("/login").defaultSuccessUrl("/",true).permitAll()).logout(l->l.logoutSuccessUrl("/login?logout")).addFilterAfter(pending,UsernamePasswordAuthenticationFilter.class);if(properties.security().oidc().enabled()&&clients.getIfAvailable()!=null)http.oauth2Login(o->o.loginPage("/login").userInfoEndpoint(u->u.oidcUserService(oidc)));return http.build();}
 @Bean CommandLineRunner bootstrapAdmin(AppUserRepository users,PasswordEncoder encoder,Smtp2xProperties p,AuditService audit){return args->{if(users.count()==0){if(p.security().initialAdminPassword()==null||p.security().initialAdminPassword().isBlank())throw new IllegalStateException("SMTP2X_ADMIN_PASSWORD is required when creating the initial administrator");AppUser admin=users.save(new AppUser(p.security().initialAdminEmail(),encoder.encode(p.security().initialAdminPassword()),UserRole.ADMIN,true,false));audit.record("system","BOOTSTRAP_ADMIN_CREATED","user",admin.getId().toString(),admin.getEmail());}};}
 @Component static class PendingUserFilter extends OncePerRequestFilter {private final AppUserRepository users;PendingUserFilter(AppUserRepository u){users=u;}protected void doFilterInternal(HttpServletRequest req,HttpServletResponse res,FilterChain chain)throws ServletException,IOException{Authentication a=org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication();if(a!=null&&a.isAuthenticated()&&!(a instanceof org.springframework.security.authentication.AnonymousAuthenticationToken)){UserRole role=users.findByEmailIgnoreCase(a.getName()).map(AppUser::getRole).orElse(UserRole.PENDING);String path=req.getRequestURI();if(role==UserRole.PENDING&&!path.equals("/pending")&&!path.equals("/logout")&&!path.startsWith("/css/")&&!path.startsWith("/js/")){res.sendRedirect("/pending");return;}}chain.doFilter(req,res);}}
}
