{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata: { name: {{ include "smtp2x.fullname" . }} }
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
