apiVersion: v2
name: smtp2x
description: SMTP notifications to GitLab issues and webhooks
type: application
version: 0.5.1
appVersion: "0.5.1"
home: https://github.com/wenisch-tech/SMTP2X
sources: ['https://github.com/wenisch-tech/SMTP2X']
annotations:
  artifacthub.io/license: AGPL-3.0
  org.opencontainers.image.source: https://github.com/wenisch-tech/helm-charts
