package tech.wenisch.smtp2x.web;
import com.fasterxml.jackson.databind.*; import jakarta.validation.Valid; import java.security.Principal; import java.util.*; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import tech.wenisch.smtp2x.domain.*; import tech.wenisch.smtp2x.repository.*; import tech.wenisch.smtp2x.service.*;
@RestController @RequestMapping("/api/v1") public class ApiController {
 private final ActionConfigurationRepository actions;private final RoutingRuleRepository rules;private final InboundMessageRepository messages;private final InboundAttachmentRepository attachments;private final DeliveryJobRepository deliveries;private final AuditEventRepository audits;private final AppUserRepository users;private final ActionConfigurationService actionService;private final DeliveryService deliveryService;private final GitLabActionHandler gitlab;private final AuditService audit;private final ObjectMapper json;
 public ApiController(ActionConfigurationRepository a,RoutingRuleRepository r,InboundMessageRepository m,InboundAttachmentRepository at,DeliveryJobRepository d,AuditEventRepository au,AppUserRepository u,ActionConfigurationService as,DeliveryService ds,GitLabActionHandler g,AuditService asd,ObjectMapper j){actions=a;rules=r;messages=m;attachments=at;deliveries=d;audits=au;users=u;actionService=as;deliveryService=ds;gitlab=g;audit=asd;json=j;}
 @GetMapping("/actions")public List<ActionView> listActions(){return actions.findAll().stream().map(this::view).toList();}@PostMapping("/actions")@PreAuthorize("hasRole('ADMIN')")public ResponseEntity<ActionView> createAction(@RequestBody ActionRequest r,Principal p){return ResponseEntity.status(201).body(view(actionService.save(null,r.name(),r.type(),r.enabled(),r.configuration(),p.getName())));}@PutMapping("/actions/{id}")@PreAuthorize("hasRole('ADMIN')")public ActionView updateAction(@PathVariable UUID id,@RequestBody ActionRequest r,Principal p){return view(actionService.save(id,r.name(),r.type(),r.enabled(),r.configuration(),p.getName()));}
 @PostMapping("/actions/gitlab/assignees/preview")@PreAuthorize("hasRole('ADMIN')")public GitLabActionHandler.AssigneePreview preview(@RequestBody AssigneePreviewRequest r)throws DeliveryException{return gitlab.previewAssignees(r.configuration(),r.recipients());}
 @GetMapping("/rules")public List<RoutingRule> listRules(){return rules.findAll();}@PostMapping("/rules")@PreAuthorize("hasRole('ADMIN')")public RoutingRule createRule(@RequestBody RuleRequest r){return rules.save(new RoutingRule(r.name(),r.globalRule(),r.recipientPattern(),r.senderPattern(),r.subjectFilter(),r.subjectMode(),r.actionIds()));}@PutMapping("/rules/{id}")@PreAuthorize("hasRole('ADMIN')")public RoutingRule updateRule(@PathVariable UUID id,@RequestBody RuleRequest r){RoutingRule rule=rules.findById(id).orElseThrow();rule.update(r.name(),r.globalRule(),r.enabled(),r.recipientPattern(),r.senderPattern(),r.subjectFilter(),r.subjectMode(),r.actionIds());return rules.save(rule);}
 @GetMapping("/messages")public List<InboundMessage> listMessages(){return messages.findAll(org.springframework.data.domain.Sort.by("receivedAt").descending());}@GetMapping("/messages/{id}")public MessageView message(@PathVariable UUID id){InboundMessage m=messages.findById(id).orElseThrow();return new MessageView(m,attachments.findByMessageId(id),deliveries.findByMessageId(id));}
 @GetMapping("/deliveries")public List<DeliveryJob> listDeliveries(){return deliveries.findAll(org.springframework.data.domain.Sort.by("updatedAt").descending());}@PostMapping("/deliveries/{id}/retry")@PreAuthorize("hasRole('ADMIN')")public void retry(@PathVariable UUID id){deliveryService.retry(id);}@PostMapping("/deliveries/{id}/cancel")@PreAuthorize("hasRole('ADMIN')")public void cancel(@PathVariable UUID id){deliveryService.cancel(id);}
 @GetMapping("/audit")public List<AuditEvent> audit(){return audits.findAll(org.springframework.data.domain.Sort.by("occurredAt").descending());}@GetMapping("/users")@PreAuthorize("hasRole('ADMIN')")public List<AppUser> users(){return users.findAll();}@PutMapping("/users/{id}/role")@PreAuthorize("hasRole('ADMIN')")public AppUser role(@PathVariable UUID id,@RequestBody RoleRequest r,Principal p){AppUser u=users.findById(id).orElseThrow();u.role(r.role());u=users.save(u);audit.record(p.getName(),"USER_ROLE_CHANGED","user",id.toString(),"role="+r.role());return u;}
 private ActionView view(ActionConfiguration a){return new ActionView(a.getId(),a.getName(),a.getType(),a.isEnabled(),actionService.publicConfiguration(a));} public record ActionRequest(String name,ActionType type,boolean enabled,JsonNode configuration){}public record ActionView(UUID id,String name,ActionType type,boolean enabled,JsonNode configuration){}public record RuleRequest(String name,boolean globalRule,boolean enabled,String recipientPattern,String senderPattern,String subjectFilter,RoutingRule.SubjectMode subjectMode,List<UUID> actionIds){}public record MessageView(InboundMessage message,List<InboundAttachment> attachments,List<DeliveryJob> deliveries){}public record RoleRequest(UserRole role){}public record AssigneePreviewRequest(JsonNode configuration,List<String> recipients){}
}
