package tech.wenisch.smtp2x.service;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.*; import java.time.*; import java.util.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import tech.wenisch.smtp2x.domain.*; import tech.wenisch.smtp2x.repository.*;
@Service public class DeliveryService {
 private final DeliveryJobRepository jobs;private final InboundMessageRepository messages;private final InboundAttachmentRepository attachments;private final ObjectMapper json;private final Map<ActionType,ActionHandler> handlers;private final AuditService audit;
 public DeliveryService(DeliveryJobRepository jobs,InboundMessageRepository messages,InboundAttachmentRepository attachments,ObjectMapper json,List<ActionHandler> handlers,AuditService audit){this.jobs=jobs;this.messages=messages;this.attachments=attachments;this.json=json;this.handlers=new EnumMap<>(ActionType.class);handlers.forEach(h->this.handlers.put(h.type(),h));this.audit=audit;}
 @Scheduled(fixedDelayString="${smtp2x.delivery.poll-ms:5000}") public void processDue(){for(DeliveryJob job:claimDue())deliver(job);}
 @Transactional List<DeliveryJob> claimDue(){List<DeliveryJob> ready=jobs.findDue(DeliveryStatus.PENDING,Instant.now()).stream().limit(20).toList();ready.forEach(DeliveryJob::claim);return ready;}
 @Transactional void deliver(DeliveryJob detached){DeliveryJob job=jobs.findById(detached.getId()).orElseThrow();if(job.getStatus()!=DeliveryStatus.RUNNING)return;try{InboundMessage message=messages.findById(job.getMessageId()).orElseThrow();List<String> recipients=json.readValue(message.getRecipientsJson(),new TypeReference<>(){});MessageData data=new MessageData(message,recipients,attachments.findByMessageId(message.getId()));JsonNode config=json.readTree(job.getConfigurationSnapshot());ActionHandler handler=handlers.get(ActionType.valueOf(config.path("type").asText("")));if(handler==null)throw new DeliveryException("No action handler configured",false);DeliveryResult result=handler.deliver(data,config.path("configuration"));job.success(result.remoteUrl(),result.diagnostics(),result.warnings());audit.record("system","DELIVERY_SUCCEEDED","delivery",job.getId().toString(),result.diagnostics());}catch(DeliveryException e){boolean retry=e.retryable()&&job.getAttempts()<4;job.fail(e.getMessage(),retry,Instant.now().plus(retryDelay(job.getAttempts())));audit.record("system",retry?"DELIVERY_RETRY":"DELIVERY_FAILED","delivery",job.getId().toString(),e.getMessage());}catch(Exception e){job.fail(e.getMessage(),false,Instant.now());audit.record("system","DELIVERY_FAILED","delivery",job.getId().toString(),String.valueOf(e.getMessage()));}}
 private Duration retryDelay(int attempts){return switch(attempts){case 0->Duration.ofMinutes(1);case 1->Duration.ofMinutes(5);case 2->Duration.ofMinutes(15);default->Duration.ofMinutes(60);};}
 public void retry(UUID id){DeliveryJob job=jobs.findById(id).orElseThrow();job.retryNow();jobs.save(job);} public void cancel(UUID id){DeliveryJob job=jobs.findById(id).orElseThrow();job.cancel();jobs.save(job);}
}
