package tech.wenisch.smtp2x.service;

import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import java.io.*; import java.net.URI; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.nio.file.Path; import java.util.*; import org.springframework.core.io.FileSystemResource; import org.springframework.http.*; import org.springframework.stereotype.Component; import org.springframework.util.*; import org.springframework.web.client.RestClient; import tech.wenisch.smtp2x.domain.*;

@Component public class GitLabActionHandler implements CleanupActionHandler {
 private final ObjectMapper json; private final SecretCipher secrets; private final ActionHttpClientFactory clients;
 public GitLabActionHandler(ObjectMapper json,SecretCipher secrets,ActionHttpClientFactory clients){this.json=json;this.secrets=secrets;this.clients=clients;}
 public ActionType type(){return ActionType.GITLAB_ISSUE;}
 public AssigneePreview previewAssignees(JsonNode config,List<String> recipients)throws DeliveryException{try{RestClient client=clients.forConfiguration(config);String base=required(config,"baseUrl").replaceAll("/$","");String token=secrets.decrypt(required(config,"accessToken"));List<String> requested=new ArrayList<>();if(config.path("useRecipient").asBoolean(false))requested.addAll(recipients);config.path("defaultAssigneeEmails").forEach(n->requested.add(n.asText()));Map<String,Long> mappings=new LinkedHashMap<>();config.path("assigneeEmailMappings").fields().forEachRemaining(e->{if(e.getValue().canConvertToLong())mappings.put(AppUser.normalize(e.getKey()),e.getValue().asLong());});List<AssigneeResolution> values=new ArrayList<>();for(String original:requested.stream().filter(s->s!=null&&!s.isBlank()).map(AppUser::normalize).distinct().toList()){Long id=mappings.get(original);if(id!=null)values.add(new AssigneeResolution(original,id,"mapping","resolved"));else{List<String>warnings=new ArrayList<>();id=lookupUser(client,base,token,original,warnings);values.add(new AssigneeResolution(original,id,"lookup",id==null?String.join("; ",warnings):"resolved"));}}return new AssigneePreview(values);}catch(DeliveryException e){throw e;}catch(Exception e){throw new DeliveryException("Could not validate GitLab assignees",true,e);}}
 public record AssigneeResolution(String email,Long gitlabUserId,String source,String status){} public record AssigneePreview(List<AssigneeResolution> resolutions){}
 public DeliveryResult deliver(MessageData data,JsonNode config)throws DeliveryException {try{
   RestClient client=clients.forConfiguration(config);
   String base=required(config,"baseUrl").replaceAll("/$","");String project=required(config,"project");String token=secrets.decrypt(required(config,"accessToken"));String api=base+"/api/v4/projects/"+URLEncoder.encode(project,StandardCharsets.UTF_8).replace("+","%20");
   List<String> requestedRaw=new ArrayList<>(); if(config.path("useRecipient").asBoolean(false))requestedRaw.addAll(data.recipients()); config.path("defaultAssigneeEmails").forEach(n->requestedRaw.add(n.asText())); final List<String> requested=requestedRaw.stream().filter(v->v!=null&&!v.isBlank()).map(AppUser::normalize).distinct().toList();
   List<Long> resolved=new ArrayList<>();List<String>warnings=new ArrayList<>();Map<String,Long> mappings=new LinkedHashMap<>();config.path("assigneeEmailMappings").fields().forEachRemaining(e->{if(e.getValue().canConvertToLong())mappings.put(AppUser.normalize(e.getKey()),e.getValue().asLong());});
   for(String email:requested){Long id=mappings.get(email);if(id==null)id=lookupUser(client,base,token,email,warnings);if(id!=null&&!resolved.contains(id))resolved.add(id);}
   String title=render(config.path("titleTemplate").asText("{{subject}}"),data);String description=render(config.path("descriptionTemplate").asText("{{body}}"),data); if(config.path("uploadAttachments").asBoolean(false))description+=uploadAttachments(client,api,token,data.attachments(),warnings);
   ObjectNode issue=json.createObjectNode();issue.put("title",title);issue.put("description",description);if(config.path("confidential").asBoolean(false))issue.put("confidential",true);if(!resolved.isEmpty()){ArrayNode ids=issue.putArray("assignee_ids");resolved.forEach(ids::add);}if(config.has("labels")&&!config.get("labels").isNull())issue.set("labels",config.get("labels"));
   JsonNode response=postJson(client,api+"/issues",token,issue); if(response==null&& !resolved.isEmpty()){warnings.add("GitLab rejected one or more assignees; issue was created without assignment.");issue.remove("assignee_ids");response=postJson(client,api+"/issues",token,issue);} if(response==null)throw new DeliveryException("GitLab rejected issue creation",false);
   List<String> returned=new ArrayList<>();response.path("assignees").forEach(n->returned.add(n.path("username").asText(n.path("id").asText()))); String iid=response.path("iid").asText();return new DeliveryResult(response.path("web_url").asText(),"GitLab issue !"+iid+" created; requested="+requested+", resolved="+resolved+", assigned="+returned,String.join("; ",warnings),iid);
 }catch(DeliveryException e){throw e;}catch(Exception e){throw new DeliveryException("GitLab delivery failed: "+safe(e.getMessage()),true,e);}}
 public void cleanup(JsonNode config,String resourceReference)throws DeliveryException {try{long iid=positiveReference(resourceReference,"GitLab issue");RestClient client=clients.forConfiguration(config);String base=required(config,"baseUrl").replaceAll("/$","");String project=required(config,"project");String token=secrets.decrypt(required(config,"accessToken"));String url=base+"/api/v4/projects/"+URLEncoder.encode(project,StandardCharsets.UTF_8).replace("+","%20")+"/issues/"+iid;client.delete().uri(URI.create(url)).header("PRIVATE-TOKEN",token).exchange((req,res)->{int status=res.getStatusCode().value();if(res.getStatusCode().is2xxSuccessful()||status==404)return null;if(status==429||status>=500)throw new DeliveryException("GitLab cleanup returned "+res.getStatusCode(),true);throw new DeliveryException("GitLab cleanup returned "+res.getStatusCode(),false);});}catch(DeliveryException e){throw e;}catch(Exception e){throw new DeliveryException("GitLab cleanup failed",true,e);}}
 private Long lookupUser(RestClient client,String base,String token,String email,List<String>warnings)throws DeliveryException {try{JsonNode list=client.get().uri(URI.create(base+"/api/v4/users?search="+URLEncoder.encode(email,StandardCharsets.UTF_8))).header("PRIVATE-TOKEN",token).exchange((req,res)->{if(res.getStatusCode().is2xxSuccessful())return json.readTree(res.getBody());if(res.getStatusCode().value()==429||res.getStatusCode().is5xxServerError())throw new DeliveryException("GitLab lookup returned "+res.getStatusCode(),true);return null;});if(list!=null)for(JsonNode user:list){String publicEmail=user.path("public_email").asText("");if(email.equalsIgnoreCase(publicEmail))return user.path("id").asLong();}warnings.add("No GitLab user resolved for "+email);return null;}catch(DeliveryException e){throw e;}catch(Exception e){throw new DeliveryException("GitLab user lookup failed",true,e);}}
 private JsonNode postJson(RestClient client,String url,String token,ObjectNode body)throws DeliveryException {try{return client.post().uri(URI.create(url)).header("PRIVATE-TOKEN",token).contentType(MediaType.APPLICATION_JSON).body(json.writeValueAsString(body)).exchange((req,res)->{if(res.getStatusCode().is2xxSuccessful())return json.readTree(res.getBody());if(res.getStatusCode().value()==400||res.getStatusCode().value()==403||res.getStatusCode().value()==404||res.getStatusCode().value()==422)return null;if(res.getStatusCode().value()==429||res.getStatusCode().is5xxServerError())throw new DeliveryException("GitLab returned "+res.getStatusCode(),true);throw new DeliveryException("GitLab returned "+res.getStatusCode(),false);});}catch(DeliveryException e){throw e;}catch(Exception e){throw new DeliveryException("GitLab request failed",true,e);}}
 private String uploadAttachments(RestClient client,String api,String token,List<InboundAttachment> items,List<String>warnings){StringBuilder markdown=new StringBuilder();for(InboundAttachment a:items)try{MultiValueMap<String,Object> form=new LinkedMultiValueMap<>();form.add("file",new FileSystemResource(Path.of(a.getContentPath())));JsonNode result=client.post().uri(URI.create(api+"/uploads")).header("PRIVATE-TOKEN",token).contentType(MediaType.MULTIPART_FORM_DATA).body(form).retrieve().body(JsonNode.class);if(result!=null)markdown.append("\n\n").append(result.path("markdown").asText());}catch(Exception ex){warnings.add("Could not upload attachment "+a.getFilename());}return markdown.toString();}
 private long positiveReference(String value,String label)throws DeliveryException{try{long result=Long.parseLong(value);if(result<=0)throw new NumberFormatException();return result;}catch(NumberFormatException e){throw new DeliveryException(label+" reference is invalid",false,e);}}
 private String required(JsonNode c,String field)throws DeliveryException{String value=c.path(field).asText();if(value.isBlank())throw new DeliveryException("GitLab action requires "+field,false);return value;} private String render(String value,MessageData data){return value.replace("{{subject}}",Optional.ofNullable(data.message().getSubject()).orElse("" )).replace("{{body}}",Optional.ofNullable(data.message().getTextBody()).orElse("")).replace("{{from}}",Optional.ofNullable(data.message().getEnvelopeFrom()).orElse("")).replace("{{recipients}}",String.join(", ",data.recipients()));}private String safe(String v){return v==null?"unknown error":v.substring(0,Math.min(v.length(),800));}
}
