package tech.wenisch.smtp2x.service;
import jakarta.mail.*; import jakarta.mail.internet.MimeMessage; import java.io.*; import java.nio.file.*; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.fasterxml.jackson.databind.ObjectMapper; import tech.wenisch.smtp2x.config.Smtp2xProperties; import tech.wenisch.smtp2x.domain.*; import tech.wenisch.smtp2x.repository.*;
@Service public class MessageIngestionService {
 private final InboundMessageRepository messages; private final InboundAttachmentRepository attachments; private final RoutingRuleRepository rules; private final ActionConfigurationRepository actions; private final DeliveryJobRepository deliveries; private final ObjectMapper json; private final Smtp2xProperties properties; private final RuleMatcher matcher; private final AuditService audit;
 public MessageIngestionService(InboundMessageRepository m,InboundAttachmentRepository a,RoutingRuleRepository r,ActionConfigurationRepository ac,DeliveryJobRepository d,ObjectMapper json,Smtp2xProperties p,RuleMatcher matcher,AuditService audit){messages=m;attachments=a;rules=r;actions=ac;deliveries=d;this.json=json;properties=p;this.matcher=matcher;this.audit=audit;}
 @Transactional public UUID accept(String envelopeFrom,List<String> recipients,byte[] raw) throws Exception {
   if(recipients==null||recipients.isEmpty())throw new IllegalArgumentException("An SMTP recipient is required");
   if(raw.length>properties.smtp().maxMessageBytes())throw new IllegalArgumentException("Message exceeds configured size");
   Parsed parsed=parse(raw); List<RoutingRule> matched=rules.findAll().stream().filter(r->matcher.matches(r,envelopeFrom,recipients,parsed.subject())).toList();
   Set<UUID> actionIds=new LinkedHashSet<>();matched.forEach(r->actionIds.addAll(r.getActionIds()));List<ActionConfiguration> selected=actions.findAllById(actionIds).stream().filter(ActionConfiguration::isEnabled).toList();
   if(selected.isEmpty())throw new IllegalArgumentException("No enabled routing action matches this message");
   InboundMessage message=new InboundMessage(envelopeFrom,json.writeValueAsString(recipients),parsed.subject(),parsed.text(),parsed.html(),"");String folder=message.getId().toString(); Path root=Path.of(properties.dataDirectory(),"messages",folder);Files.createDirectories(root);Path source=root.resolve("message.eml");Files.write(source,raw,StandardOpenOption.CREATE_NEW);message.contentPath(source.toString());
   message=messages.save(message); for(AttachmentData data:parsed.attachments()){Path path=Path.of(properties.dataDirectory(),"messages",message.getId().toString(),"attachments",safeName(data.filename()));Files.createDirectories(path.getParent());Files.write(path,data.bytes(),StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);attachments.save(new InboundAttachment(message.getId(),data.filename(),data.contentType(),path.toString(),data.bytes().length));}
   for(ActionConfiguration action:selected){var snapshot=json.createObjectNode();snapshot.put("type",action.getType().name());snapshot.set("configuration",json.readTree(action.getConfigurationJson()));deliveries.save(new DeliveryJob(message.getId(),action.getId(),json.writeValueAsString(snapshot)));}
   audit.record("smtp","MESSAGE_ACCEPTED","message",message.getId().toString(),"rules="+matched.stream().map(RoutingRule::getName).toList()+", actions="+selected.stream().map(ActionConfiguration::getName).toList());return message.getId();
 }
 private Parsed parse(byte[] raw)throws Exception{MimeMessage mime=new MimeMessage(Session.getInstance(new Properties()),new ByteArrayInputStream(raw));Parts parts=new Parts();collect(mime,parts);return new Parsed(Optional.ofNullable(mime.getSubject()).orElse("(no subject)"),parts.text,parts.html,parts.attachments);}
 private void collect(Part part,Parts result)throws Exception{if(part.isMimeType("multipart/*")){Multipart mp=(Multipart)part.getContent();for(int i=0;i<mp.getCount();i++)collect(mp.getBodyPart(i),result);return;} String disposition=part.getDisposition();String filename=part.getFileName();if(filename!=null||Part.ATTACHMENT.equalsIgnoreCase(disposition)){try(InputStream in=part.getInputStream()){result.attachments.add(new AttachmentData(filename==null?"attachment":filename,part.getContentType(),in.readAllBytes()));}return;}if(part.isMimeType("text/plain")&&result.text==null)result.text=String.valueOf(part.getContent());else if(part.isMimeType("text/html")&&result.html==null)result.html=String.valueOf(part.getContent());}
 private String safeName(String s){return s.replaceAll("[^a-zA-Z0-9._-]","_");} private record AttachmentData(String filename,String contentType,byte[] bytes){} private record Parsed(String subject,String text,String html,List<AttachmentData> attachments){} private static class Parts{String text;String html;List<AttachmentData> attachments=new ArrayList<>();}
}
