package tech.wenisch.smtp2x.service;
import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.nio.file.attribute.PosixFilePermission; import java.security.SecureRandom; import java.util.*; import javax.crypto.*; import javax.crypto.spec.GCMParameterSpec; import javax.crypto.spec.SecretKeySpec; import org.springframework.stereotype.Service; import tech.wenisch.smtp2x.config.Smtp2xProperties;
@Service public class SecretCipher {
 private final SecretKey key; private final SecureRandom random=new SecureRandom();
 public SecretCipher(Smtp2xProperties properties){String configured=properties.crypto().key();String value=configured==null||configured.isBlank()?loadOrCreate(Path.of(properties.dataDirectory(),"encryption.key")):configured;byte[] bytes=Base64.getDecoder().decode(value.trim());if(bytes.length!=32)throw new IllegalStateException("SMTP2X_CRYPTO_KEY must be a base64 encoded 32-byte AES key");key=new SecretKeySpec(bytes,"AES");}
 private String loadOrCreate(Path path){try{if(Files.exists(path))return Files.readString(path,StandardCharsets.US_ASCII);Files.createDirectories(path.getParent());byte[] bytes=new byte[32];random.nextBytes(bytes);String value=Base64.getEncoder().encodeToString(bytes);try{Files.writeString(path,value,StandardCharsets.US_ASCII,StandardOpenOption.CREATE_NEW);try{Files.setPosixFilePermissions(path,Set.of(PosixFilePermission.OWNER_READ,PosixFilePermission.OWNER_WRITE));}catch(UnsupportedOperationException ignored){}}catch(FileAlreadyExistsException ignored){return Files.readString(path,StandardCharsets.US_ASCII);}return value;}catch(Exception e){throw new IllegalStateException("Cannot create SMTP2X encryption key at "+path,e);}}
 public String encrypt(String value){if(value==null||value.isBlank())return "";try{byte[] iv=new byte[12];random.nextBytes(iv);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key,new GCMParameterSpec(128,iv));return "enc:"+Base64.getEncoder().encodeToString(iv)+":"+Base64.getEncoder().encodeToString(c.doFinal(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("Cannot encrypt secret",e);}}
 public String decrypt(String value){if(value==null||value.isBlank())return "";if(!value.startsWith("enc:"))return value;try{String[] p=value.split(":",3);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key,new GCMParameterSpec(128,Base64.getDecoder().decode(p[1])));return new String(c.doFinal(Base64.getDecoder().decode(p[2])),StandardCharsets.UTF_8);}catch(Exception e){throw new IllegalStateException("Cannot decrypt secret",e);}}
}
